### PR TITLE
code cleanup

### PR DESCRIPTION
**Pull request by just-ero**
smile

### CODE REVIEW

**Comment by KunoDemetries** [comment]
Imagine doing all this just to have it denied, get a life

**Comment by ero-qt** [comment]
Imagine being so conservative that you can't even accept improvements in coding.

**Comment by KunoDemetries** [comment]
imagine not understanding nobody wants your help

**Comment by rythin-sr** [comment]
kuno just take the L like half of your asls straight up dont fucking work man

**Comment by KunoDemetries** [comment]
hey rythin maybe stop having your friends do shit and you can message me, you turned into a POS so fuck off

**Comment by KunoDemetries** [comment]
Also, when literally *all of them fucking work* and people *verify they work* I'm not going to believe you because the logical changes he added literally don't fix fuck all

**Pull request closed without merging**
